import { Proyecto } from './types';

export const PROYECTOS_DATA: Proyecto[] = [
  {
    id: 'vistas-san-damian',
    nombre: 'Vistas de San Damián II',
    comuna: 'Machalí',
    region: 'vi',
    entrega: 'inmediata',
    precioDesdeUF: 9600,
    imagenUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    descripcion: 'arquitectura mediterránea, iluminación natural de nivel superior y materiales constructivos de primera calidad.',
    caracteristicas: ['diseño higiénico-térmico', 'luz natural garantizada', 'materiales nobles premium', 'amplio patio privado'],
    dormitorios: 3,
    banos: 3,
    superficie: 140,
    terreno: 380,
    ejecutivaNombre: 'ailleen muñoz',
    ejecutivaFono: '+56952027697'
  },
  {
    id: 'nexus-vespucio',
    nombre: 'Edificio Nexus Vespucio',
    comuna: 'La Cisterna',
    region: 'rm',
    entrega: 'inmediata',
    precioDesdeUF: 2100,
    imagenUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    descripcion: 'ubicación estratégica con conectividad total, diseño moderno pensado para vivir de forma óptima o realizar inversión segura.',
    caracteristicas: ['excelente conectividad metro', 'arquitectura urbana óptima', 'alta rentabilidad estimada', 'seguridad inteligente'],
    dormitorios: 3,
    banos: 2,
    superficie: 72,
    ejecutivaNombre: 'ludmila dávila c.',
    ejecutivaFono: '+56722765659'
  },
  {
    id: 'haras-polo',
    nombre: 'Haras Polo de Machalí',
    comuna: 'Machalí',
    region: 'vi',
    entrega: 'inmediata',
    precioDesdeUF: 5650,
    imagenUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    descripcion: 'sofisticado estilo mediterráneo enclavado en el sector exclusivo el polo. máxima comodidad y seguridad en el mejor entorno.',
    caracteristicas: ['urbanización de lujo subterránea', 'canchas de polo cercanas', 'acceso controlado premium', 'arquitectura contemporánea'],
    dormitorios: 3,
    banos: 3,
    superficie: 140,
    terreno: 220,
    ejecutivaNombre: 'noelia osorio',
    ejecutivaFono: '+56934396154'
  },
  {
    id: 'vista-sur-iv',
    nombre: 'Vista Sur IV',
    comuna: 'Rancagua',
    region: 'vi',
    entrega: 'futura',
    precioDesdeUF: 2910,
    imagenUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    descripcion: 'hermosas casas de un piso, ubicadas estratégicamente a pasos del hospital regional de rancagua. máxima comodidad garantizada.',
    caracteristicas: ['viviendas de un piso', 'cercano a hospital regional', 'áreas verdes integradas', 'excelente conectividad'],
    dormitorios: 3,
    banos: 2,
    superficie: 85,
    ejecutivaNombre: 'claudy aponte',
    ejecutivaFono: '+56938607327'
  },
  {
    id: 'los-prunos',
    nombre: 'Los Prunos',
    comuna: 'Lo Barnechea',
    region: 'rm',
    entrega: 'futura',
    precioDesdeUF: 11900,
    imagenUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    descripcion: 'condominio exclusivo de tan solo 8 casas, con un impecable diseño de vanguardia integrado de manera armónica en áreas verdes.',
    caracteristicas: ['exclusividad absoluta de 8 casas', 'diseño moderno de autor', 'entorno montañoso nativo', 'máxima seguridad perimetral'],
    dormitorios: 3,
    banos: 4,
    superficie: 157,
    ejecutivaNombre: 'ludmila dávila',
    ejecutivaFono: '+56966618238'
  },
  {
    id: 'ayres-pinares',
    nombre: 'Ayres de Pinares',
    comuna: 'Pichilemu / Matanzas',
    region: 'vi',
    entrega: 'vendido',
    precioDesdeUF: 25500,
    imagenUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    descripcion: 'maravilloso e imponente proyecto totalmente vendido. casas mediterráneas de lujo absoluto con vistas ininterrumpidas sobre el océano pacífico.',
    caracteristicas: ['vistas al pacífico de 180°', 'frente de acantilado directo', 'bosque nativo privado', 'arquitectura de escala mundial'],
    dormitorios: 5,
    banos: 5,
    superficie: 372,
    terreno: 611,
    ejecutivaNombre: 'noelia osorio',
    ejecutivaFono: '+56934396154'
  }
];
